- name: create jenkins Jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    folders:
      - { folder_name: "CI-pipelines" }
      - { folder_name: "Infra-Jobs" }
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/Vivekdevops1704/cart" , folder_name: "CI-pipelines" }
      - { job_name: "catalogue", repo_name: "https://github.com/Vivekdevops1704/catalogue" , folder_name: "CI-pipelines" }
      - { job_name: "shipping", repo_name: "https://github.com/Vivekdevops1704/shipping" , folder_name: "CI-pipelines" }
      - { job_name: "user", repo_name: "https://github.com/Vivekdevops1704/user" , folder_name: "CI-pipelines" }
      - { job_name: "payment", repo_name: "https://github.com/Vivekdevops1704/payment" , folder_name: "CI-pipelines" }
      - { job_name: "frontend", repo_name: "https://github.com/Vivekdevops1704/frontend" , folder_name: "CI-pipelines" }
      - { job_name: "dispatch", repo_name: "https://github.com/Vivekdevops1704/dispatch" , folder_name: "CI-pipelines" }    
    sjobs:
      - { job_name: "roboshop-terraform",repo_name: "https://github.com/Vivekdevops1704/roboshop-terraform" , folder_name: "Infra-Jobs" }
