- name: create jenkins Jobs
  hosts: localhost
  roles:
    - jenkins
  vars:
    mjobs:
      - { job_name: "cart", repo_name: https://github.com/Vivekdevops1704/cart" }
    sjobs:
      - { job_name: "roboshop-terraform",repo_name: "https://github.com/Vivekdevops1704/roboshop-terraform" }