- name: copy config file - {{ item.folder_name }}
  ansible.builtin.template:
    src: folders.xml
    dest: /tmp/folders.xml

- name: Create job - {{ item.folder_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folders.xml') }}"
    name: "{{ item.job_name }}"
    password: admin123
    url: http://172.31.46.106:8080
    user: admin
