#- name: create multibranch jobs
#  ansible.builtin.include_tasks:
 #   file: mjob.yml
 # loop: "{{ mjobs }}"

- name: create singlebranch jobs
  ansible.builtin.include_tasks:
    file: sjob.yml
  loop:  "{{ sjobs }}"
