- name: copy config file - {{ item.job_name }}
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/sjob.xml

- name: Create job - {{ item.job_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sjob.xml') }}"
    name: "{{ item.job_name }}"
    password: admin123
    url: https://54.198.70.16:8080
    user: admin